import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

// https://astro.build/config
export default defineConfig({
	integrations: [
		starlight({
			title: 'SDVM',
			logo: {
				src: './src/assets/sdvm-logo.jpeg',
			  },
			customCss: [
				'./src/styles/custom.css',
			  ],
			  social: {
				  github: 'https://github.com/withastro/starlight',
			  },
			sidebar: [
				{
					label: 'Guides',
					items: [
						// Each item here is one entry in the navigation menu.
						{ label: 'Example Guide', link: '/guides/example/' },
					],
				},
				{
					label: 'Honours',
					autogenerate: { directory: 'Honours' },
					items: [
						{label:'Botany' ,
					autogenerate:{  directory: 'Botany' },
					items:[{label:'Semester1',
					autogenerate:{  directory: 'Semester1' }},
					{label:'Semester2',
					autogenerate:{  directory: 'Semester2' }},
					{label:'Semester3',
					autogenerate:{  directory: 'Semester3' }},
					{label:'Semester4',
					autogenerate:{  directory: 'Semester4' }},
					{label:'Semester5',
					autogenerate:{  directory: 'semester5' }},
					{label:'Semester6',
					autogenerate:{  directory: 'semester6' }},
					],
				},
			
					{label:'Chemistry' ,
					autogenerate:{  directory: 'Chemistry' },
					items:[{label:'Semester1',
					autogenerate:{  directory: 'Semester1' }},
					{label:'Semester2',
					autogenerate:{  directory: 'Semester2' }},
					{label:'Semester3',
					autogenerate:{  directory: 'Semester3' }},
					{label:'Semester4',
					autogenerate:{  directory: 'Semester4' }},
					{label:'Semester5',
					autogenerate:{  directory: 'semester5' }},
					{label:'Semester6',
					autogenerate:{  directory: 'semester6' }},
					],
				},
					{label:'Math' ,
					autogenerate:{  directory: 'Math' },
					items:[{label:'Semester1',
					autogenerate:{  directory: 'Semester1' }},
					{label:'Semester2',
					autogenerate:{  directory: 'Semester2' }},
					{label:'Semester3',
					autogenerate:{  directory: 'Semester3' }},
					{label:'Semester4',
					autogenerate:{  directory: 'Semester4' }},
					{label:'Semester5',
					autogenerate:{  directory: 'semester5' }},
					{label:'Semester6',
					autogenerate:{  directory: 'semester6' }},
					],
				},
					{label:'Physics' ,
					autogenerate:{  directory: 'Physics' },
					items:[{label:'Semester1',
					autogenerate:{  directory: 'Semester1' }},
					{label:'Semester2',
					autogenerate:{  directory: 'Semester2' }},
					{label:'Semester3',
					autogenerate:{  directory: 'Semester3' }},
					{label:'Semester4',
					autogenerate:{  directory: 'Semester4' }},
					{label:'Semester5',
					autogenerate:{  directory: 'semester5' }},
					{label:'Semester6',
					autogenerate:{  directory: 'semester6' }},
					],
			},
					{label:'Zoology' ,
					autogenerate:{  directory: 'Zoology' },
					items:[{label:'Semester1',
					autogenerate:{  directory: 'Semester1' }},
					{label:'Semester2',
					autogenerate:{  directory: 'Semester2' }},
					{label:'Semester3',
					autogenerate:{  directory: 'Semester3' }},
					{label:'Semester4',
					autogenerate:{  directory: 'Semester4' }},
					{label:'Semester5',
					autogenerate:{  directory: 'semester5' }},
					{label:'Semester6',
					autogenerate:{  directory: 'semester6' }},
					],
				},

					],
				},
			],
		}),
	],
});
