import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

// https://astro.build/config
export default defineConfig({
	integrations: [
		starlight({
			title: 'SDVM',
			logo: {
				src: './src/assets/sdvm-logo.jpeg',
			  },
			customCss: [
				'./src/styles/custom.css',
			  ],
			  social: {
				  github: 'https://github.com/withastro/starlight',
			  },
			sidebar: [
				{
					label: 'Guides',
					items: [
						// Each item here is one entry in the navigation menu.
						{ label: 'Example Guide', link: '/guides/example/' },
					],
				},
				{
					label: 'Honours',
					autogenerate: { directory: 'Honours' },
					items: [
						{ label:'Botany' ,
					autogenerate:{  directory: 'Botany' },
					items:[{ label:'Semester1',
					autogenerate:{  directory: 'Semester1' },
					items:[{ label:'core1',
					autogenerate:{  directory: 'core1' },
				items:[{ label:'Pratice set1', link: 'honours/botany/sem1/core1/set1'}]},],
				items:[{ label:'core2',
				autogenerate:{  directory: 'core2' },
			items:[{ label:'Pratice set2', link: 'honours/botany/sem1/core2/set2'}]}
					],},
					{ label:'Semester2',
					autogenerate:{  directory: 'Semester2' },
					items:[{ label:'core3',
					autogenerate:{  directory: 'core3' },
				items:[{ label:'Pratice set3', link: 'honours/botany/sem2/core3/set3'}]},],
				items:[{ label:'core4',
				autogenerate:{  directory: 'core4' },
			items:[{ label:'Pratice set4', link: 'honours/botany/sem2/core4/set4'}]}
					],},
					{ label:'Semester3',
					autogenerate:{  directory: 'Semester3' },
					items:[{ label:'core5',
					autogenerate:{  directory: 'core5' },
				items:[{ label:'Pratice set5', link: 'honours/botany/sem3/core5/set5'}]},],
				items:[{ label:'core6',
				autogenerate:{  directory: 'core6' },
			items:[{ label:'Pratice set6', link: 'honours/botany/sem3/core6/set6'}]},],
			items:[{ label:'core7',
			autogenerate:{  directory: 'core7' },
		    items:[{ label:'Pratice set7 ', link: 'honours/botany/sem3/core7/set7'}]}
					],},
					{ label:'Semester4',
					autogenerate:{  directory: 'Semester4' },
					items:[{ label:'core8',
					autogenerate:{  directory: 'core8' },
				items:[{ label:'Pratice set8', link: 'honours/botany/sem4/core8/set8'}]},],
				items:[{ label:'core9',
				autogenerate:{  directory: 'core9' },
				items:[{ label:'Pratice set9 ', link: 'honours/botany/sem4/core9/set9'}]},],
				items:[{ label:'core10',
				autogenerate:{  directory: 'core10' },
				items:[{ label:'Pratice set10 ', link: 'honours/botany/sem4/core10/set10'}]}
						],},
					{ label:'Semester5',
					autogenerate:{  directory: 'semester5' },
					items:[{ label:'core11',
					autogenerate:{  directory: 'core11' },
					items:[{ label:'Pratice set11 ', link: 'honours/botany/sem5/core11/set11'}]},],
					items:[{ label:'core12',
					autogenerate:{  directory: 'core12' },
					items:[{ label:'Pratice set12 ', link: 'honours/botany/sem5/core12/set12'}]}],
					items:[{ label:'DSE1',
					autogenerate:{  directory: 'DSE1' },
					items:[{ label:'Pratice set13 ', link: 'honours/botany/sem5/DSE1/set13'}]},],
					items:[{ label:'DSE2',
					autogenerate:{  directory: 'DSE2' },
					items:[{ label:'Pratice set14 ', link: 'honours/botany/sem4/DSE2/set14'}]}],},
					{ label:'Semester6',
					autogenerate:{  directory: 'semester6' },
					items:[{ label:'core13',
					autogenerate:{  directory: 'core13' },
					items:[{ label:'Pratice set15 ', link: 'honours/botany/sem6/core13/set15'}]}],
					items:[{ label:'core14',
					autogenerate:{  directory: 'core14' },
					items:[{ label:'Pratice set16 ', link: 'honours/botany/sem6/core14/set16'}]}],
					items:[{ label:'DSE3',
					autogenerate:{  directory: 'DSE3' },
					items:[{ label:'Pratice set17 ', link: 'honours/botany/sem4/DSE3/set17'}]},],
					items:[{ label:'DSE4',
					autogenerate:{  directory: 'DSE4' },
					items:[{ label:'Pratice set18 ', link: 'honours/botany/sem4/DSE4/set18'}]},],},
					],
				},
					{ label:'Chemistry' ,
					autogenerate:{  directory: 'Chemistry' },
					items:[{ label:'Semester1',
					autogenerate:{  directory: 'Semester1' }},
					{ label:'Semester2',
					autogenerate:{  directory: 'Semester2' }},
					{ label:'Semester3',
					autogenerate:{  directory: 'Semester3' }},
					{ label:'Semester4',
					autogenerate:{  directory: 'Semester4' }},
					{ label:'Semester5',
					autogenerate:{  directory: 'semester5' }},
					{ label:'Semester6',
					autogenerate:{  directory: 'semester6' }},
					],
				},
					{ label:'Math' ,
					autogenerate:{  directory: 'Math' },
					items:[{ label:'Semester1',
					autogenerate:{  directory: 'Semester1' }},
					{ label:'Semester2',
					autogenerate:{  directory: 'Semester2' }},
					{ label:'Semester3',
					autogenerate:{  directory: 'Semester3' }},
					{ label:'Semester4',
					autogenerate:{  directory: 'Semester4' }},
					{ label:'Semester5',
					autogenerate:{  directory: 'semester5' }},
					{ label:'Semester6',
					autogenerate:{  directory: 'semester6' }},
					],
				},
					{ label:'Physics' ,
					autogenerate:{  directory: 'Physics' },
					items:[{ label:'Semester1',
					autogenerate:{  directory: 'Semester1' }},
					{ label:'Semester2',
					autogenerate:{  directory: 'Semester2' }},
					{ label:'Semester3',
					autogenerate:{  directory: 'Semester3' }},
					{ label:'Semester4',
					autogenerate:{  directory: 'Semester4' }},
					{ label:'Semester5',
					autogenerate:{  directory: 'semester5' }},
					{ label:'Semester6',
					autogenerate:{  directory: 'semester6' }},
					],
			},
					{ label:'Zoology' ,
					autogenerate:{  directory: 'Zoology' },
					items:[{ label:'Semester1',
					autogenerate:{  directory: 'Semester1' }},
					{ label:'Semester2',
					autogenerate:{  directory: 'Semester2' }},
					{ label:'Semester3',
					autogenerate:{  directory: 'Semester3' }},
					{ label:'Semester4',
					autogenerate:{  directory: 'Semester4' }},
					{ label:'Semester5',
					autogenerate:{  directory: 'semester5' }},
					{ label:'Semester6',
					autogenerate:{  directory: 'semester6' }},
					],
				},

					],
				},
			],
		}),
	],
});
